version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
  app:
    build: .
    environment:
      - PORT
      - HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_DIALECT
      - DB_STORAGE
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
      - "9230:9230"
    tty: true
